plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = 'com.github.catvod'

    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId = "com.github.catvod.demo"
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
    }

    buildFeatures {
        viewBinding = true
    }

    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    configurations.configureEach {
        resolutionStrategy {
            force "com.squareup.okhttp3:okhttp:${libs.versions.okhttp.get()}"
        }
        exclude group: 'xpp3', module: 'xpp3'
        exclude group: 'net.sf.kxml', module: 'kxml2'
        exclude group: 'xmlpull', module: 'xmlpull'
    }
    lint {
        checkReleaseBuilds = false
        abortOnError = false
    }
}

dependencies {
    implementation libs.okhttp
    implementation libs.sardine.android
    implementation libs.quickjs.wrapper
    implementation libs.gson
    implementation libs.smbj
    implementation libs.jsoup
    implementation(libs.logger) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    implementation libs.jsr305
    implementation libs.juniversalchardet
    implementation libs.jsoup.xpath
    implementation libs.nanohttpd
    implementation libs.zxing.core
    implementation libs.jetbrains.annotations
    implementation files('libs/tvboxserver.aar')
}
